### ISSUE TITLE
Difficulties installing in Rocky linux

### ISSUE THREAD

**Issue by ttyr2** [novafacile/novagallery#9]
Rocky Linux 8.5 fully updated.
Installed httpd, php, php-json
Extracted contents of novagallery to the /html default apache path, not as a sub-directory.
Renamed and edited site.php file with URL=http://192.168.0.54 (IP of temporary server)

When accessing the site, I am seeing the basic novagallery page with broken images for gallery place holders (for the image directories), but titles of those directories are showing. When I click on any of them, I receive a 404 error.

I'm able to navigate directly to the images and view them singly via a web browser. A simple php script to display the contents of one of the galleries also shows all the pictures in one of the directories (granted, with no thumbnails or resizing).

Looking for pointers
![novagallery_error1](https://user-images.githubusercontent.com/103903695/163731915-62dbd7b7-e786-4369-9122-a2046c5abe92.JPG)
![novagallery_error2](https://user-images.githubusercontent.com/103903695/163731916-50123e2f-5806-44d5-a9c1-67b94ef1d9cb.JPG)
.

**Comment by david-novafacile** [comment]
Hello,

Missing thumbnails:
- there was a bug in the last version, it was just fixed, please download the latest version: https://download.novafacile.com/novagallery/novagallery-free.zip
- If the bug occurs also in the new version: is php-gd lib installed? And if so, how much memory can php use?

Album not accessible:
- This looks like the htaccess file is not allowed to be read (apache configuration). In this file the mod_rewrite configuration is set, which redirects every request to the script.

**Comment by ttyr2** [comment]
I downloaded the updated version and am seeing the same result. One of the things I noticed was that index.php puts up the directory thumbnails (which are still broken) by pointing at <web root>/galleries, but when you click one of the directories it tries to go to <web root>/albums which doesn't exist in the file structure.

**Comment by david-novafacile** [comment]
> but when you click one of the directories it tries to go to <web root>/albums which doesn't exist in the file structure.

Yes, the directory /album does not exists. This is handled by the index.php. But you have to enable mod_rewrite in apache and that .htaccess can override the apache settings in vhost (`AllowOverride All`)

This also is needed for the thumbnails generation.

**Comment by howardlshippin** [comment]
I just downloaded and tried to use in MXLinux 21, on a newly installed home server.  I have the same problem. Php version is  7.4.28.  GD and Exif are installed (https://vikshepa.com/phpinfo.php).  Apache Module rewrite is enabled (a2enmod rewrite) and AllowOverride All is enabled for the specific site.  I tried renaming ImagesDirName from "galleries" to "albums" and changing the directory name via Filezilla in case that might change something.
